[phases.setup]
nixPkgs = ["python311", "gcc"]

[phases.install]
cmds = ["python -m venv --copies /opt/venv && . /opt/venv/bin/activate && pip install uv"]

[phases.build]
cmds = ["uv sync", "uv pip install -e ."]
onlyIncludeFiles = ["pyproject.toml", "uv.lock"]

[start]
cmd = "uv run fastapi run src/api/main.py --port=13364"